import type { Address, Hex } from "viem";
export type Token = {
  address: Address;
  creator: Address;
  name: string;
  symbol: string;
  decimals: number;
  quote: Address;
  pool_id: Hex;
  initial_tick: number;
  image: string;
  description: string;
  website: string;
  twitter: string;
  telegram: string;
  discord: string;
  editable: boolean;
  launched_at: string;
  launch_tx: Hex;
  salt_uint: string;
  suffix: string;
  token_stats?: TokenStats | null;
};
export type TokenStats = {
  address: Address;
  price_quote: number | null;
  initial_price_quote: number | null;
  price_usd: number | null;
  initial_price_usd: number | null;
  fdv_quote: number | null;
  fdv_usd: number | null;
  liquidity_quote: number | null;
  volume_24h: number | null;
  volume_lifetime: number | null;
  trades_24h: number;
  trades_lifetime: number;
  price_change_24h: number | null;
  current_tick: number | null;
  last_trade_at: string | null;
  holders: number | null;
  updated_at: string;
};
export type Trade = {
  id: string;
  token: Address;
  tx: Hex;
  block_number: number;
  timestamp: string;
  trader: Address;
  side: "buy" | "sell";
  amount_token: string;
  amount_quote: string;
  quote_delta: string;
  price_quote: number | null;
  price_usd: number | null;
  tick: number | null;
  indexer_version?: number;
};
export const text = (v?: string | null) => (v && v.trim()) || "";
export const label = (v?: string | null) => (v && v.trim()) || "-";
